language: node_js

dist: trusty

if: branch = master

before_script:
 - echo "JAVA_HOME=/usr/local/openjdk-8" > .env
 - echo "WORKING_DIR=/tmp" >> .env

script:
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 - docker build -t asn1-playground .
 - docker images
 - docker tag asn1-playground "$DOCKER_USERNAME"/asn1-playground
 - docker push "$DOCKER_USERNAME"/asn1-playground
