language: node_js

dist: trusty

jobs:
  include:
    - if: branch = master
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t asn1-playground .
      - docker images
      - docker tag asn1-playground "$DOCKER_USERNAME"/asn1-playground
      - docker push "$DOCKER_USERNAME"/asn1-playground
