language: node_js

dist: trusty

if: tag IS present

env:
- TOOL_VERSION=v0.0.23

before_script:
 - echo "JAVA_HOME=/usr/local/openjdk-8" > .env
 - echo "WORKING_DIR=/tmp" >> .env
 - echo "ASN1_COMPILER_JAR=/usr/src/app/asn1-compiler-with-google-java-format.jar" >> .env
 - echo "ASN1_CONVERTER_JAR=/usr/src/app/asn1-converter.jar" >> .env
 - echo "ASN1_RUNTIME_JAR=/usr/src/app/asn1-runtime.jar" >> .env
 - wget https://github.com/yafred/asn1-tool/releases/download/$TOOL_VERSION/asn1-compiler-with-google-java-format.jar
 - wget https://github.com/yafred/asn1-tool/releases/download/$TOOL_VERSION/asn1-converter.jar
 - wget https://github.com/yafred/asn1-tool/releases/download/$TOOL_VERSION/asn1-runtime.jar
 
script:
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 - docker build -t "$DOCKER_USERNAME"/asn1-playground .
 - docker images
 - docker push "$DOCKER_USERNAME"/asn1-playground
