
name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Checkout the repository
        uses: actions/checkout@v2
      - 
        name: Get artifacts
        run: |
          wget https://github.com/yafred/asn1-tool/releases/download/v0.0.28/asn1-compiler-with-google-java-format.jar
          wget https://github.com/yafred/asn1-tool/releases/download/v0.0.28/asn1-converter.jar
          wget https://github.com/yafred/asn1-tool/releases/download/v0.0.28/asn1-runtime.jar
      - 
        name: Create .env 
        run: |
          echo "JAVA_HOME=/usr/lib/jvm/default-java/" > .env
          echo "WORKING_DIR=/tmp" >> .env
          echo "ASN1_COMPILER_JAR=/usr/src/app/asn1-compiler-with-google-java-format.jar" >> .env
          echo "ASN1_CONVERTER_JAR=/usr/src/app/asn1-converter.jar" >> .env
          echo "ASN1_RUNTIME_JAR=/usr/src/app/asn1-runtime.jar" >> .env
          echo "VERSION=v0.0.28" >> .env
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: yafred/asn1-playground:test

      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
