
name: release

# on events
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout the repository
        uses: actions/checkout@v2
      - 
        name: Set env
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - 
        name: Get artifacts
        run: |
          wget https://github.com/yafred/asn1-tool/releases/download/${{env.VERSION}}/asn1-compiler-with-google-java-format.jar
          wget https://github.com/yafred/asn1-tool/releases/download/${{env.VERSION}}/asn1-converter.jar
          wget https://github.com/yafred/asn1-tool/releases/download/${{env.VERSION}}/asn1-runtime.jar
      - 
        name: Create .env 
        run: |
          echo "JAVA_HOME=/usr/lib/jvm/default-java/" > .env
          echo "WORKING_DIR=/tmp" >> .env
          echo "ASN1_COMPILER_JAR=/usr/src/app/asn1-compiler-with-google-java-format.jar" >> .env
          echo "ASN1_CONVERTER_JAR=/usr/src/app/asn1-converter.jar" >> .env
          echo "ASN1_RUNTIME_JAR=/usr/src/app/asn1-runtime.jar" >> .env
          echo "VERSION=${{env.VERSION}}" >> .env
          ls -al
      -
        name: Build
        run: |
          docker build -t yafred/asn1-playground:test .
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Push
        run: |
          docker push yafred/asn1-playground:test
 
